routes/web.php
    $this->get('new-category', 'NewCategoryController@index')->name('new-category.index');
    $this->post('new-category/getdata', 'NewCategoryController@getData')->name('new-category.getdata');

    $this->resource('new-subcategory', 'NewSubCategoryController');
    $this->post('new-subcategory/getdata', 'NewSubCategoryController@getData')->name('new-subcategory.getdata');
    $this->post('new-subcategory/ajax-subcategory', 'NewServiceController@ajaxSubcategory')->name('new-subcategory.ajax');

    $this->resource('new-service', 'NewServiceController');
    $this->post('new-service/getdata', 'NewServiceController@getData')->name('new-service.getdata');

    $this->resource('subservice', 'SubServiceController');
    $this->post('subservice/getdata', 'SubServiceController@getData')->name('subservice.getdata');

    $this->post('subservice/ajax-services', 'SubServiceController@ajaxSubcategoryservice')->name('subservices.ajax');

    $this->resource('service-attribute', 'ServiceAttributeController');
    $this->post('service-attribute/getdata', 'ServiceAttributeController@getData')->name('service-attribute.getdata');

    $this->resource('fitness-type', 'FitnessTypeController');
    $this->post('fitness-type/getdata', 'FitnessTypeController@getData')->name('fitness-type.getdata');
    
    //------------------------------------------------------------
    $this->resource('amenity', 'AmenityController');
    $this->post('amenity/getdata', 'AmenityController@getData')->name('amenity.getdata');

    $this->resource('tier', 'TierController');
    $this->post('tier/getdata', 'TierController@getData')->name('tier.getdata');

    $this->get('category', 'CategoryController@index')->name('category.index');
    $this->post('category/getdata', 'CategoryController@getData')->name('category.getdata');

    $this->resource('subcategory', 'SubCategoryController');
    $this->post('subcategory/getdata', 'SubCategoryController@getData')->name('subcategory.getdata');

    $this->post('subcategory/ajax-subcategory', 'ServiceController@ajaxSubcategory')->name('subcategory.ajax');

    $this->resource('service', 'ServiceController');
    $this->post('service/getdata', 'ServiceController@getData')->name('service.getdata');

    $this->resource('staff', 'StaffController');
    $this->post('staff/getdata', 'StaffController@getData')->name('staff.getdata');
    $this->post('staff/banner-delete', 'StaffController@deleteImageVideos')->name('staff.destroy-file');

    $this->resource('gallery', 'GalleryController');
    $this->post('gallery/getdata', 'GalleryController@getData')->name('gallery.getdata');

    $this->resource('banners', 'BannersController');
    $this->post('banners/getdata', 'BannersController@getData')->name('banners.getdata');
    $this->post('/banners/changeStatus', 'BannersController@StatusUpdate')->name('banners.status.update');

    $this->resource('product', 'ProductController');
    $this->post('product/getdata', 'ProductController@getData')->name('product.getdata');

    $this->resource('tag', 'TagController');
    $this->post('tag/getdata', 'TagController@getData')->name('tag.getdata');

    $this->resource('testimonial', 'TestimonialController');
    $this->post('testimonial/getdata', 'TestimonialController@getData')->name('testimonial.getdata');

    $this->resource('page-section', 'PageSectionController');
    $this->post('page-section/getdata', 'PageSectionController@getData')->name('page-section.getdata');
    $this->post('/page-section/changeStatus', 'PageSectionController@StatusUpdate')->name('page-section.status.update');

    $this->resource('occasion', 'OccasionController');
    $this->post('occasion/getdata', 'OccasionController@getData')->name('occasion.getdata');

    $this->resource('gift-theme', 'GiftThemeController');
    $this->post('gift-theme/getdata', 'GiftThemeController@getData')->name('gifttheme.getdata');
    $this->post('/gift-theme/makePublish', 'GiftThemeController@PublishUpdate')->name('gifttheme.publish.update');

    $this->resource('faq-category', 'FaqCategoryController');
    $this->post('faq-category/getdata', 'FaqCategoryController@getData')->name('faq-category.getdata');

    $this->resource('faq', 'FaqController');
    $this->post('faq/getdata', 'FaqController@getData')->name('faq.getdata');

    $this->resource('contact', 'ContactController');
    $this->post('contact/getdata', 'ContactController@getData')->name('contact.getdata');

    $this->resource('e-card', 'ECardController');
    $this->post('e-card/getdata', 'ECardController@getData')->name('e-card.getdata');
    $this->any('e-card/cancel', 'ECardController@cancel')->name('e-card.cancel');
    $this->get('cancelled-card-view/{id}', 'ECardController@cancelled_card_view')->name('e-card.cancelled_card_view');
    //------------------------offer routes--------------------
    $this->resource('offer', 'OfferController');
    $this->post('offer/getdata', 'OfferController@getData')->name('offer.getdata');

    $this->get('service-provider/pending/offer', 'SpOffersController@pendingOffers')->name('sp.pending.offer');

    $this->get('service-provider/approved/offer', 'SpOffersController@approvedOffers')->name('sp.approved.offer');

    $this->get('service-provider/expired/offer', 'SpOffersController@expiredOffers')->name('sp.expired.offer');

    $this->get('service-provider/spectacular/offer', 'SpOffersController@spectacularOffers')->name('sp.spectacular.offer');


    $this->post('sp/offer/getdata', 'SpOffersController@getData')->name('sp.offer.getdata');
    $this->get('sp/offer/edit/{id}/{name}', 'SpOffersController@edit')->name('sp.offer.edit');
    $this->get('sp/offer/nominate/{id}/{offer_status}', 'SpOffersController@nominateOffer')->name('sp.offer.nominate');
     $this->PATCH('sp/offer/update/{id}', 'SpOffersController@updateOffer')->name('sp.offer.update');

    $this->get('sp/offer/decline/{id}', 'SpOffersController@declineOffer')->name('sp.offer.decline');
    $this->get('sp/offer/view/{id}/{name}', 'SpOffersController@viewOffer')->name('sp.offer.view');
    $this->post('sp/offer/update/nominate/{id}', 'SpOffersController@updateNominateOffer')->name('sp.offer.update.nominate');
     $this->any('sp/offer/destroy/{id}', 'SpOffersController@destroy')->name('sp.offer.destroy');
     $this->post('sp/offer/changeStatus', 'SpOffersController@StatusUpdate')->name('sp.offer.status.update');
     $this->post('sp/offer/changeFeaturedStatus', 'SpOffersController@FeaturedStatusUpdate')->name('sp.offer.featuredstatus.update');

    $this->get('service-provider/services/{id}', 'SpServicesController@index')->name('sp.service.index');
    $this->get('service-provider/services/banner/{id}', 'ServiceProviderController@banner')->name('sp.service.banner');
    $this->post('sp/services/getdata', 'SpServicesController@getData')->name('sp.services.getdata');
    $this->get('sp/services/view/{id}', 'SpServicesController@view')->name('sp.services.view');

    //------------------------offer routes--------------------

   $this->resource('quickFact', 'QuickFactController');
   $this->post('quickFact/getdata', 'QuickFactController@getData')->name('quickFact.getdata');
   $this->post('get-quickFact-subcategory', 'QuickFactController@ajaxSubcategory')->name('get-quickFact-subcategory');
   $this->post('get-quickFact-services', 'QuickFactController@ajaxGetSubcatServices')->name('get-quickFact-services');
   $this->post('get-quickFact-sub-services', 'QuickFactController@ajaxGetSubcatSubServices')->name('get-quickFact-sub-services');

   $this->post('quickfact/banner-delete', 'QuickFactController@deleteBannerImage')->name('quickfact.banner-image-delete');

   $this->resource('reviews', 'ReviewsController');
   $this->post('reviews/getdata', 'ReviewsController@getData')->name('reviews.getdata');
   $this->post('reviews/get-sp-staff-service', 'ReviewsController@getSpStaffServices')->name('get-sp-staff-service');
   $this->post('reviews/ajax-get-sp-searched-staff-service', 'ReviewsController@ajaxGetSpSearchedStaffServices')->name('ajax-get-sp-searched-staff-service');
   $this->post('reviews/filter', 'ReviewsController@getCustomerReviewsFilter')->name('ajax.review.filter');

    $this->post('reviews/status', 'ReviewsController@StatusUpdate')->name('review.status.update');

    $this->get('reviews/show/overall/{sp_id}', 'ReviewsController@showOverallSpReviews')->name('sp.overall.reviews');
    
    $this->get('customer/forum', 'ForumController@index')->name('forum.index');
    $this->post('/forum/get-queries', 'ForumController@getData')->name('forum.queries');
    $this->any('/forum/delete-queries/{slug}', 'ForumController@deleteForumQueries')->name('forum.queries.delete');
    $this->any('/forum/show/{slug}', 'ForumController@viewQuery')->name('forum.queries.view');
    $this->any('/forum/delete/{slug}', 'ForumController@deleteForumComment')->name('forum.comment.delete');
    $this->any('/forum/approve-status/{slug}', 'ForumController@approveForumStatus')->name('forum.queries.approve-status');
    $this->any('/forum/reject-status/{slug}', 'ForumController@rejectForumStatus')->name('forum.queries.reject-status');

    $this->resource('spectacularOffer', 'SpectacularOfferTypeController');
    $this->post('spectacularOffer/getdata', 'SpectacularOfferTypeController@getData')->name('spectacularOffer.getdata');

    $this->resource('promocode', 'PromoCodeController');
    $this->post('promocode/getdata', 'PromoCodeController@getData')->name('promocode.getdata');
    $this->post('/promocode/changeStatus', 'PromoCodeController@StatusUpdate')->name('promo.status.update');
    $this->get('promocode/promo-log/{id}', 'PromoCodeController@promo_log')->name('promocode.promo-log');
    

    $this->get('settings', 'SettingController@index')->name('setting.index');
    $this->post('settings/getdata', 'SettingController@getData')->name('setting.getdata');
    $this->any('settings/edit/{id}', 'SettingController@edit')->name('setting.edit');

resources/views/admin/page_section/create.blade.php
@extends('layouts.admin.admin')

@section('uniquecss')

  <link rel="stylesheet" href="{{ url('/') }}/assets/lib/plupload/js/jquery.plupload.queue/css/jquery.plupload.queue.css">
  <link rel="stylesheet" href="{{ url('/') }}/assets/lib/jquery.gritter/css/jquery.gritter.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/Uniform.js/2.1.2/themes/default/css/uniform.default.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.theme.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/validationEngine.jquery.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.2/croppie.min.css">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
@endsection

@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <header class="dark">
                <div class="icons"><i class="fa fa-check"></i></div>
                <h5>{{$title}}</h5>
          

            </header>
             @include('message')
            <div id="collapse2" class="body">
                <!-- <form class="form-horizontal" id="popup-validation"> -->
                {!! Form::open(['route' => 'page-section.store', 'method' => 'POST', 'class' => 'form-horizontal','id' => 'popup-validation','enctype' => 'multipart/form-data']) !!}
                {{ csrf_field() }}

                    <div class="form-group">
                        {{Form::label('page_name', 'Page Name', ['class' => 'control-label col-lg-4'])}}
                        <div class="col-lg-4">
                            {{ Form::select('page_name', $page_name_array,null,['class' => 'form-control validate[required] myselect', 'id'=>"page_name",'placeholder' => 'Select Page Name']) }}
                        </div>
                    </div>
                    <div class="form-group">
                        {{Form::label('page_section_name', __('messages.Section Name'), ['class' => 'control-label col-lg-4'])}}
                        <div class="col-lg-4">
                            {{ Form::select('page_section_name', $all_page_sections,null,['class' => 'form-control validate[required] myselectTags']) }}
                        </div>
                    </div>
                    <div class="form-group">
                        {{Form::label('title', __('messages.Title'), ['class' => 'control-label col-lg-4'])}}
                        <div class="col-lg-4">
                            {{ Form::text('title','', ['class' => 'form-control']) }}
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="control-label col-lg-4">{{ __('messages.Image') }}</label>
                        <div class="row">
                            <div class="col-md-4">
                                <div id="ImgView">
                                    <img src="">
                                </div>
                                <div id="upload-demo" style=" display: none;"></div>
                            
                                <input class="form-control" type="file" id="image" onclick="showHideDiv(this)" name="image" accept="image/*">
                                <?= Form::hidden('image_cr',null, ['id' => 'image_cr']) ?>
                            </div>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        {{Form::label('description', __('messages.Description'), ['class' => 'control-label col-lg-4'])}}
                        <div class="col-lg-4">
                            {{ Form::textarea('description','', ['class' => 'form-control validate[required] summary-ckeditor','rows'=>'2']) }}
                        </div>
                    </div>

                    <div class="form-actions no-margin-bottom">
                        <input type="submit" value="{{ __('messages.Submit') }}" class="btn btn-primary">
                    </div>
                    <br><br><br><br>
                </form>
            </div>
        </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
@endsection
@section('uniquescript')
    <script src="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/jquery.validationEngine.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/languages/jquery.validationEngine-en.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/holder/2.4.1/holder.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/Uniform.js/2.1.2/jquery.uniform.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.2/croppie.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <script src="{{ url('/') }}/assets/lib/ckeditor/ckeditor.js"></script>
    <script type="text/javascript">
        function showHideDiv()
        {
            $('#ImgView').hide();
            $('#upload-demo').show();
        }
        $(function() {
           $(".myselectTags").select2({
            tags: true,
            closeOnSelect : false,
            allowHtml: true,
            allowClear: true,
            placeholder : 'Select Section Name'
           });
        });
    </script>
    <script>
        CKEDITOR.replace( 'description' );
        $(function() {
          Metis.formValidation();
        });

        function isNumber(evt) {
            var charCode = (evt.which) ? evt.which : event.keyCode
            if (charCode > 31 && (charCode < 48 || charCode > 57)) {
                return false;
            }
            return true;
        }

        $('#popup-validation').submit(function(e){
            e.preventDefault();
            obj = $(this);
            resize.croppie('result', {
                type: 'canvas',
                size: 'viewport'
            }).then(function (img) {
                $('#image_cr').val(img);
               obj.unbind('submit').submit();
            });
        });

        // image crop
        var resize = $('#upload-demo').croppie({
            enableExif: true,
            enableOrientation: true,    
            viewport: { // Default { width: 100, height: 100, type: 'square' } 
                width: 200,
                height: 200,
                type: 'square' //square
            },
            boundary: {
                width: 300,
                height: 300
            }
        });

        $('#image').on('change', function () { 
          var reader = new FileReader();
            reader.onload = function (e) {
              resize.croppie('bind',{
                url: e.target.result
              }).then(function(){
                console.log('jQuery bind complete');
              });
            }
            reader.readAsDataURL(this.files[0]);
        });
        // 
    </script>


@endsection

resources/views/admin/page_section/edit.blade.php
@extends('layouts.admin.admin')

@section('uniquecss')

  <link rel="stylesheet" href="{{ url('/') }}/assets/lib/plupload/js/jquery.plupload.queue/css/jquery.plupload.queue.css">
  <link rel="stylesheet" href="{{ url('/') }}/assets/lib/jquery.gritter/css/jquery.gritter.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/Uniform.js/2.1.2/themes/default/css/uniform.default.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.theme.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/validationEngine.jquery.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.2/croppie.min.css">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />

@endsection

@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <header class="dark">
                <div class="icons"><i class="fa fa-check"></i></div>
                <h5>{{$title}}</h5>
          

            </header>
             @include('message')
            <div id="collapse2" class="body">
                <!-- <form class="form-horizontal" id="popup-validation"> -->
                {!! Form::model($rows,['route' => ['page-section.update',$rows->id], 'method' => 'PATCH', 'class' => 'form-horizontal','id' => 'popup-validation','enctype' => 'multipart/form-data']) !!}
                {{ csrf_field() }}
                    <div class="form-group">
                        {{Form::label('page_name', 'Page Name', ['class' => 'control-label col-lg-4'])}}
                        <div class="col-lg-4">
                            {{ Form::select('page_name', $page_name_array,null,['class' => 'form-control validate[required] myselect', 'id'=>"page_name",'placeholder' => 'Select Page Name']) }}
                        </div>
                    </div>
                    <div class="form-group">
                        {{Form::label('page_section_name', __('messages.Section Name'), ['class' => 'control-label col-lg-4'])}}
                        <div class="col-lg-4">
                            {{ Form::select('page_section_name', $all_page_sections,null,['class' => 'form-control validate[required] myselectTags']) }}
                        </div>
                    </div>
                    
                    <div class="form-group">
                        {{Form::label('title', __('messages.Title'), ['class' => 'control-label col-lg-4'])}}
                        <div class="col-lg-4">
                            {{ Form::text('title',null, ['class' => 'form-control']) }}
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-lg-4">{{ __('messages.Image') }}</label>
                        <div class="row">
                            <div class="col-md-4">
                                <div id="ImgView">
                                    @if($rows->image!='')
                                      <img src="{{changeImageUrlForFileExist(asset('sp_uploads/pages/'.$rows->page_name.'/'.$rows->image))}}" alt="..." height="200" width="200">
                                    @else
                                      <img src="{{asset('images/defualt.jpeg')}}" alt="..." height="200" width="200">
                                    @endif
                                </div><br>
                                <div id="upload-demo" style="display: none;"></div>
                                <input class="form-control" type="file" id="image" onclick="showHideDiv(this)" name="image" accept="image/*">
                                <?= Form::hidden('image_cr',null, ['id' => 'image_cr']) ?>
                            </div>   
                        </div>
                    </div>

                    <div class="form-group">
                        {{Form::label('description', __('messages.Description'), ['class' => 'control-label col-lg-4'])}}
                        <div class="col-lg-4">
                            {{ Form::textarea('description',null, ['class' => 'form-control validate[required] summary-ckeditor','rows'=>'2']) }}
                        </div>
                    </div>
                    
                    <div class="form-actions no-margin-bottom">
                        <input type="submit" value="{{ __('messages.Submit') }}" class="btn btn-primary">
                    </div>
                    <br><br><br><br>
                </form>
            </div>
        </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
@endsection
@section('uniquescript')
    <script src="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/jquery.validationEngine.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/languages/jquery.validationEngine-en.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/holder/2.4.1/holder.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/Uniform.js/2.1.2/jquery.uniform.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.2/croppie.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <script src="{{ url('/') }}/assets/lib/ckeditor/ckeditor.js"></script>
    <script type="text/javascript">
        function showHideDiv()
        {
            $('#ImgView').hide();
            $('#upload-demo').show();
        }
        $(function() {
           $(".myselectTags").select2({
            tags: true,
            closeOnSelect : false,
            allowHtml: true,
            allowClear: true,
            placeholder : 'Select Section Name'
           });
        });
        
    </script>
    <script>
        CKEDITOR.replace( 'description' );
        $(function() {
          Metis.formValidation();
        });

        function isNumber(evt) {
            var charCode = (evt.which) ? evt.which : event.keyCode
            if (charCode > 31 && (charCode < 48 || charCode > 57)) {
                return false;
            }
            return true;
        }
        
        $('#popup-validation').submit(function(e){
            e.preventDefault();
            obj = $(this);
            resize.croppie('result', {
                type: 'canvas',
                size: 'viewport'
            }).then(function (img) {
                $('#image_cr').val(img);
               obj.unbind('submit').submit();
            });
        });

        // image crop
        var resize = $('#upload-demo').croppie({
            enableExif: true,
            enableOrientation: true,    
            viewport: { // Default { width: 100, height: 100, type: 'square' } 
                width: 200,
                height: 200,
                type: 'square' //square
            },
            boundary: {
                width: 300,
                height: 300
            }
        });
        $('#image').on('change', function () { 
          var reader = new FileReader();
            reader.onload = function (e) {
              resize.croppie('bind',{
                url: e.target.result
              }).then(function(){
                console.log('jQuery bind complete');
              });
            }
            reader.readAsDataURL(this.files[0]);
        });
        // 
    </script>


@endsection

resources/views/admin/page_section/index.blade.php
@extends('layouts.admin.admin')
@section('uniquecss')

  <link rel="stylesheet" href="{{ url('/') }}/assets/lib/sweetalert/sweetalert.css">
 
@endsection
@section('content')
  <div class="row">
  <div class="col-lg-12">
        <div class="box">
            <header>
                <div class="icons"><i class="fa fa-table"></i></div>
                <h5>{{ __('messages.Page Section table') }}</h5>
                <a class="btn btn-primary pull-right" href="{{route('page-section.create')}}" style="margin-top:4px;">{{ __('messages.Create Page') }}</a>
            </header>
            <div id="collapse4" class="body">
              @include('message')
              
               <table id="user_datatable" class="table table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>{{ __('messages.Page Name') }}</th>
                        <th>{{ __('messages.Section Name') }}</th>
                        <th>{{ __('messages.Title') }}</th>
                        <th>{{ __('messages.Image') }}</th>
                        <th>{{ __('messages.Status') }}</th>
                        <th>{{ __('messages.Action') }}</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
                  
            </div>
        </div>
    </div>
</div>
@endsection

@section('uniquescript')
<script src="{{asset('assets/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('assets/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{asset('assets/lib/sweetalert/sweetalert.js')}}"></script>
<script type="text/javascript">

  function deleteRow(obj)
  {
    event.preventDefault(); // prevent form submit
    swal({
      title: "{{ __('messages.Are you sure?') }}",
      type: "warning",
      showCancelButton: true,
      confirmButtonColor: "#DD6B55",
      confirmButtonText: "Yes",
      cancelButtonText: "No",
      closeOnConfirm: false,
      closeOnCancel: false
    },
    function(isConfirm){
      if (isConfirm) {        
       obj.submit();

      } else {
         swal.close();
      }
    });
  }
  
  function changeStatus(id)
  {
    swal({
        title: "Are you sure?",
        type: "warning",
        showCancelButton: "No",
        confirmButtonClass: "btn-danger",
        confirmButtonText: "Yes",
        cancelButtonText: "No",
      },
        function(){
          jQuery.ajax({
          url: '{{route('page-section.status.update')}}',
          type: 'POST',
          data:{page_id:id},
          headers: {
          'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
          },
          success: function (response) {
            $("#status_"+id).html(response);
          }
          });
        }
    );
  }
    $(function() {
        var table = $('#user_datatable').DataTable({
           stateSave: true,
        processing: true,
        serverSide: true,
        order: [[0, "desc" ]],
        "ajax":{
        "url": '{!! route('page-section.getdata') !!}',
                "dataType": "json",
                "type": "POST",
                "data":{ _token: "{{csrf_token()}}"}
        },
        columns: [
        { data: 'page_name', name: 'page_name', orderable:true },
        { data: 'page_section_name', name: 'page_section_name', orderable:true },
        { data: 'title', name: 'title', orderable:true },
        { data: 'image', name: 'image', orderable:true },
        { data: 'status', name: 'status', orderable:true },
        { data: 'action', name: 'action', orderable:true  },
        ],
        "columnDefs": [
        { "searchable": false, "targets": 0 }
        ]
        , language: {
        searchPlaceholder: "{{ __('messages.Search by page name and title') }}"
        },
});
});  


</script>
@endsection