routes/web.php
    $this->get('complete-orders', 'OrdersController@completeOrders')->name('orders.complete');
    $this->post('orders/getdataComplete', 'OrdersController@getDataComplete')->name('orders.getdataComplete');
    $this->post('orders/cancel', 'OrdersController@cancel')->name('orders.cancel');
    $this->get('cancelled-orders', 'OrdersController@cancelledOrders')->name('orders.cancelled');
    $this->post('orders/getcancelled', 'OrdersController@getCancelled')->name('orders.getcancelled');
    $this->get('cancelled-order-view/{id}/{flag?}', 'OrdersController@cancelled_order_view')->name('orders.cancelled_order_view');
    $this->get('/orders/order-chat-history/{id}/{flag?}', 'OrdersController@orderChatHistory')->name('orders.orderChatHistory');
    $this->get('/custompages', 'CustomPagesController@index')->name('custompages.index');
    $this->post('/custompages/getdata', 'CustomPagesController@getData')->name('custompages.getdata');
    $this->get('/custompages/edit/{slug}', 'CustomPagesController@edit')->name('custompages.edit');
    $this->post('/custompages/update', 'CustomPagesController@update')->name('custompages.update');
    

    $this->any('sp-unpaid-settlements', 'OrdersController@sp_unpaid_settlements')->name('orders.sp_unpaid_settlements');
    $this->post('orders/getDataSpUnpaid', 'OrdersController@getDataSpUnpaid')->name('orders.getDataSpUnpaid');
    $this->get('unpaid-settlements/{id}', 'OrdersController@unpaid_settlements')->name('orders.unpaid_settlements');
    $this->post('orders/getdataUnpaid', 'OrdersController@getDataUnpaid')->name('orders.getdataUnpaid');
    $this->any('confirm-settlements', 'OrdersController@confirm_settlements')->name('orders.confirm-settlements');
    $this->post('orders/save-settlements', 'OrdersController@save_settlements')->name('orders.save-settlements');
    $this->post('orders/offline-settlements', 'OrdersController@offline_settlements')->name('orders.offline-settlements');
    $this->get('paid-settlements', 'OrdersController@paid_settlements')->name('orders.paid_settlements');
    $this->post('orders/getdataPaid', 'OrdersController@getDataPaid')->name('orders.getdataPaid');
    $this->any('orders/view-settlement/{slug}/{flag?}', 'OrdersController@view_settlement')->name('orders.view-settlement');
    $this->get('transaction-history', 'OrdersController@transaction_history')->name('orders.transaction_history');
    $this->post('orders/getdataHistory', 'OrdersController@getDataHistory')->name('orders.getdataHistory');
    $this->get('orders/view-history/{id}', 'OrdersController@view_history')->name('orders.view_history');
    $this->get('aesthetic-orders', 'OrdersController@aesthetic_orders')->name('orders.aesthetic_orders');
    $this->post('orders/getaestheticData', 'OrdersController@getAestheticData')->name('orders.getaestheticData');
    $this->get('orders/view-aesthetic/{id}', 'OrdersController@view_aesthetic')->name('orders.view_aesthetic');
    $this->post('orders/save-aesthetic', 'OrdersController@save_aesthetic')->name('orders.save-aesthetic');
    $this->get('contact/view/{id}', 'ContactController@view')->name('contact.view');
    $this->post('contact/save-contact', 'ContactController@save_contact')->name('contact.save-contact');

    /*------------------------------ Store Trail Sessions Route ---------------------------------------------*/
    $this->resource('trail-session', 'TrailSessionController');
    $this->post('trail-session/getdata', 'TrailSessionController@getData')->name('trail-session.getdata');
    $this->resource('trail-session-faq', 'TrailSessionFaqController');
    $this->post('trail-session-faq/getdata', 'TrailSessionFaqController@getData')->name('trail-session-faq.getdata');
    $this->get('trail-session-faq/view/{spid}/{userid}/{sessionid}', 'TrailSessionFaqController@view')->name('trail-session-faq.view');
    $this->post('trail-session/delete-question/{slug}', 'TrailSessionController@deleteSessionQuestion')->name('trail-session.delete-question');
});

$this->group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'AdminBeforeLoggedIn'], function () {
    
    $this->get('/', 'AdminController@login')->name('admin.login');
    $this->get('/login', 'AdminController@login')->name('admin.login');
    $this->post('/login', 'AdminController@checklogin')->name('admin.make.login');
    
});

$this->group([ 'namespace' => 'Front'], function () {

    $this->get('/user-email-confirmation', 'UserController@userEmailConfirmation')->name('front.confirm.email');
    $this->get('/forgot-password', 'UserController@forgotPassword')->name('front.forgotpassword');
    $this->post('/forgot-password', 'UserController@checkForgotPasswordEmail')->name('front.make.forgotPassword');
    $this->any('/forgot-password-page/{token}', 'UserController@forgotPassPage')->name('front.forgot.page');
    $this->post('/update-forgot-password', 'UserController@updateForgotPassword')->name('update-forgot-password');

     //for service provider
     $this->get('sp/user-email-confirmation', 'UserController@spUserEmailConfirmation')->name('front.sp.confirm.email');
     $this->get('/forgotPassword', 'SpUserController@forgotPassword')->name('front.sp.forgotpassword');

    $this->post('/forgotPassword', 'SpUserController@checkForgotPasswordEmail')->name('front.sp.make.forgotPassword');
    $this->any('/forgotPassword-page/{token}', 'SpUserController@forgotPassPage')->name('front.sp.forgot.page');
    $this->post('/update-forgotPassword', 'SpUserController@updateForgotPassword')->name('sp.update-forgot-password');


     $this->get('/service-provider/signup', 'SpUserController@signup')->name('front.sp.signup');
     $this->post('/service-provider/signup', 'SpUserController@makeSignup')->name('front.sp.make.signup');
     $this->get('/service-provider/check-otp', 'SpUserController@checkOtp')->name('front.sp.check.otp');
     $this->post('/service-provider/registration', 'SpUserController@registerServiceProvider')->name('front.sp.registration');

     $this->get('pages/{slug}', 'CustomPageViewController@showPages')->name('show-custom-page');
     // $this->any('alert-page', 'CustomPageViewController@alertPage')->name('custom-alert-page');

     $this->any('payment/ipnlistener', 'PaytabController@ipnListener')->name('payment.ipn.listener');
     $this->any('payment/log', 'PaytabController@paymentLog')->name('payment.log');

      $this->get('generate-pdf/{orderid}', 'PdfGenerateController@orderInvoice')->name('generate-pdf');
      $this->get('app_redirect', 'CustomPageViewController@app_redirect')->name('app_redirect');
      $this->get('sp_app_redirect', 'CustomPageViewController@sp_app_redirect')->name('sp_app_redirect');
      $this->get('shopdetail/{sp_id}', 'CustomPageViewController@shopdetail_redirect')->name('shopdetail');
      $this->get('refercode/{refer_code}', 'CustomPageViewController@refercode_redirect')->name('refercode');
      $this->get('offerdetail/{offer_id}/{sp_id}', 'CustomPageViewController@offerdetail')->name('offerdetail');
      $this->get('/', 'CustomPageViewController@rootRedirect')->name('rootRedirect');

});


//routes for service provider admin

$this->group(['prefix' => 'service-provider', 'namespace' => 'SpAdmin', 'middleware' => 'SpAdminLoggedIn'], function () {

    $this->get('/', 'PagesController@dashboard')->name('spadmin.dashboard');
    $this->get('/dashboard', 'PagesController@dashboard')->name('spadmin.dashboard');
    $this->get('logoutt', 'UserController@logout')->name('spadmin.logout');

    $this->get('/changePassword', 'UserController@changePassword')->name('spuser.change-password');
    $this->post('/updatePassword', 'UserController@doUpdatePassword')->name('spuser.update-password');

    $this->post('/delete-banner-image', 'UserController@deleteBannerImage')->name('spuser.banner-image-delete');

    $this->get('/shop-timings', 'UserController@showShopTiming')->name('spuser.shop-timings');

    $this->post('/update-shop-timings', 'UserController@updateShopTimings')->name('spuser.update-shop-timings');

    $this->get('/edit-profile', 'UserController@edit')->name('spuser.edit-profile');
    $this->get('/gallery', 'UserController@gallery')->name('spuser.gallery');
    $this->post('/update', 'UserController@update')->name('spuser.update');
    $this->post('/update-gallery', 'UserController@updateGallery')->name('spuser.update-gallery');

    $this->resource('my-gallery', 'GalleryController');
    $this->post('my-gallery/getdata', 'GalleryController@getData')->name('my-gallery.getdata');

    $this->resource('staffs', 'StaffController');
    //$this->get('staffs', 'StaffController@index')->name('staffs.index');
    $this->post('staff/getdata', 'StaffController@getData')->name('staffs.getdata');
    $this->post('/delete-staff-image', 'StaffController@deleteImageVideos')->name('spuser.staff-destroy-file');

    $this->post('get-state-list', 'UserController@getStateList')->name('spuser.get-state-list');
    $this->post('get-city-list', 'UserController@getCityList')->name('spuser.get-city-list');

    $this->resource('products', 'ProductController');
    $this->post('product/getdata', 'ProductController@getData')->name('products.getdata');

    $this->get('/agreement', 'AgreementController@index')->name('spuser.agreement');
    $this->post('/agreement/home-service', 'AgreementController@addMov')->name('spuser.mov');

    $this->resource('services', 'ServiceController');
    $this->post('services/getdata', 'ServiceController@getData')->name('services.getdata');
    $this->post('ajax/getServices', 'ServiceController@ajaxGetSubcatServices')->name('ajax.get.services');

    $this->post('ajax/addServiceData', 'ServiceController@ajaxAddServiceData')->name('ajax.add.service.data');

    $this->post('ajax/check/homeService', 'ServiceController@checkProvideHomeService')->name('ajax.check.home.service');

    $this->post('service/active/homeService', 'ServiceController@activeHomeService')->name('home.service.active');

resources/views/admin/trail_session/create.blade.php
@extends('layouts.admin.admin')

@section('uniquecss')

  <link rel="stylesheet" href="{{ url('/') }}/assets/lib/plupload/js/jquery.plupload.queue/css/jquery.plupload.queue.css">
  <link rel="stylesheet" href="{{ url('/') }}/assets/lib/jquery.gritter/css/jquery.gritter.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/Uniform.js/2.1.2/themes/default/css/uniform.default.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.theme.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/validationEngine.jquery.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.2/croppie.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
@endsection

@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <header class="dark">
                <div class="icons"><i class="fa fa-check"></i></div>
                <h5>{{__('messages.'.$title)}}</h5>
          

            </header>
             @include('message')
            <div id="collapse2" class="body">
                <!-- <form class="form-horizontal" id="popup-validation"> -->
                {!! Form::open(['route' => 'trail-session.store', 'method' => 'POST', 'class' => 'form-horizontal','id' => 'trail-session','enctype' => 'multipart/form-data']) !!}
                {{ csrf_field() }}
                    
                    <div class="form-group">
                        {{Form::label('name', __('messages.Session Name'), ['class' => 'control-label col-lg-4'])}}
                        <div class="col-lg-4">
                            {{ Form::text('name','', ['class' => 'form-control validate[required]','maxlength'=>'50']) }}
                        </div>
                    </div>
                    
                    <div class="form-group">
                        {{Form::label('question', __('messages.Question'), ['class' => 'control-label col-lg-4'])}}
                        <div class="col-lg-4">
                            <div class="input-group">
                                {{ Form::text('question[]','', ['class' => 'form-control validate[required]']) }}
                                <div class="input-group-addon"></div>
                            </div>
                            <br>
                            <div id="items"></div>
                        </div>
                    </div>
                    <div class="form-group" style="text-align: right">
                      <label for="addmore" class="control-label col-lg-4"></label>
                      <div class="col-lg-4" >
                        <a href="#" id="addmore">{{ __('messages.Add More') }}</a>
                      </div>
                    </div>
                    <div class="form-actions no-margin-bottom">
                        <input type="submit" value="Submit" class="btn btn-primary">
                    </div>
                    <br><br><br><br>
                </form>
            </div>
        </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
@endsection
@section('uniquescript')
    <script src="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/jquery.validationEngine.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/languages/jquery.validationEngine-en.min.js"></script>

     <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/holder/2.4.1/holder.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/Uniform.js/2.1.2/jquery.uniform.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.2/croppie.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>

    
    <script>
        $(function() {
          Metis.formValidation();
        });

        $(document).ready(function() {
            var max_fields = 20; //maximum input boxes allowed
            var wrapper = $("#items"); //Fields wrapper
            var add_button = $("#addmore"); //Add button ID

            var x = 1; //initlal text box count
            $(add_button).click(function(e)
            { //on add input button click
                e.preventDefault();
                if(x < max_fields){ //max input box allowed
                x++; //text box increment
                $(wrapper).append('<div class="input-group question_group"><input class="form-control" name="question[]" type="text"><div class="input-group-addon"><button type="button" style="padding: 0px 4px;" class="btn btn-danger btn-sm remove_field"><i class="fa fa-close" aria-hidden="true"></i></button></div></div><br>');
            }
            });
             
            $(wrapper).on("click",".remove_field", function(e){ //user click on remove field
              e.preventDefault(); 
              $(this).parent().closest('.question_group').next('br').remove(); 
              $(this).parent().closest('.question_group').empty();
              x--;
            })
        });
    </script>
@endsection

resources/views/admin/trail_session/edit.blade.php
@extends('layouts.admin.admin')

@section('uniquecss')

  <link rel="stylesheet" href="{{ url('/') }}/assets/lib/plupload/js/jquery.plupload.queue/css/jquery.plupload.queue.css">
  <link rel="stylesheet" href="{{ url('/') }}/assets/lib/jquery.gritter/css/jquery.gritter.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/Uniform.js/2.1.2/themes/default/css/uniform.default.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.theme.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/validationEngine.jquery.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.2/croppie.min.css">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="{{ url('/') }}/assets/lib/sweetalert/sweetalert.css">
@endsection

@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <header class="dark">
                <div class="icons"><i class="fa fa-check"></i></div>
                <h5>{{__('messages.'.$title)}}</h5>
            </header>
             @include('message')
            <div id="collapse2" class="body">
                <!-- <form class="form-horizontal" id="popup-validation"> -->
                {!! Form::model($rows,['route' => ['trail-session.update',$rows->id], 'method' => 'PATCH', 'class' => 'form-horizontal','id' => 'trail-session','enctype' => 'multipart/form-data']) !!}
                {{ csrf_field() }}

                    <div class="form-group">
                        {{Form::label('name', __('messages.Session Name'), ['class' => 'control-label col-lg-4'])}}
                        <div class="col-lg-4">
                            {{ Form::select('trail_session_id', $session_list,$rows['id'],['class' => 'form-control validate[required] myselect','placeholder'=>'Select Session']) }}
                        </div>
                    </div>
                    <div class="form-group">
                        {{Form::label('question', __('messages.Question'), ['class' => 'control-label col-lg-4'])}}
                        <div class="col-lg-4">
                          @foreach($questionList as $id => $list)
                            {{ Form::text('question['.$id.']',$list, ['class' => 'form-control validate[required]']) }}
                            <br>
                          @endforeach
                          <div id="items"></div>
                        </div>
                    </div>
                    <!--<div class="form-group">
                        {{Form::label('question', __('messages.Question'), ['class' => 'control-label col-lg-4'])}}
                          <div class="col-lg-4">
                            @php
                            $count = 0;
                              //$count = $questionList['count'];
                              unset($questionList['count']);
                            @endphp
                            @foreach($questionList as $id => $list)
                            <div class="input-group">
                              {{ Form::text('question['.$id.']',$list, ['class' => 'form-control validate[required]']) }}
                              <div class="input-group-addon">
                                <a style="padding: 0px 4px;" class="btn btn-danger btn-sm delete-question" data-id ="{{ $id }}" data-count="{{ $count }}" href="{{ route('trail-session.delete-question', ['id' => $id]) }}" data-method="DELETE"> <i class="fa fa-trash-o" aria-hidden="true"></i></a>  
                              </div>
                            </div>
                            <br>
                            @endforeach
                            <div id="items"></div>
                          </div>
                    </div>-->
                    <div class="form-group" style="text-align: right">
                      <label for="addmore" class="control-label col-lg-4"></label>
                      <div class="col-lg-4" >
                        <a href="#" id="addmore">{{ __('messages.Add More') }}</a>
                      </div>
                    </div>

                    <div class="form-actions no-margin-bottom">
                        <input type="submit" value="Submit" class="btn btn-primary">
                    </div>
                    <br><br><br><br>
                </form>
            </div>
        </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
@endsection
@section('uniquescript')
    <script src="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/jquery.validationEngine.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/languages/jquery.validationEngine-en.min.js"></script>

     <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/holder/2.4.1/holder.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/Uniform.js/2.1.2/jquery.uniform.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.2/croppie.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <script src="{{asset('assets/lib/sweetalert/sweetalert.js')}}"></script>

    <script type="text/javascript">
      var numItems = $('.delete-question').length;
      if(numItems == 1){
        $(".delete-question").attr("href", "#");
        $("a").removeClass("delete-question");
      }
      $(document).on('click', '.delete-question', function (e)
      {
        var url = $(this).attr('href');
        var id = $(this).attr('data-id');
        var asso = $(this).attr('data-count');
        console.log(url);
        e.preventDefault(); // prevent form submit
        var msg = "Are you sure ?";
        if(asso > 0){
            var msg = "You cannot delete this Question because this is associated with User Faq.";
        }
        if(asso > 0){ 
          swal({
              title: msg,
              type: "warning",
              showCancelButton: true,
              showConfirmButton: false,
              confirmButtonColor: "#DD6B55",
              confirmButtonText: "Yes",
              cancelButtonText: "Ok",
              closeOnConfirm: false,
              closeOnCancel: false,

          },
          function(isConfirm){
            if (isConfirm) {        
              //obj.submit();

            } else {
               swal.close();
            }
          });
        }
        else{
          swal({
              title: msg,
              type: "warning",
              showCancelButton: true,
              confirmButtonColor: "#DD6B55",
              confirmButtonText: "Yes",
              cancelButtonText: "No",
              closeOnConfirm: false,
              closeOnCancel: false,

          },
          function(isConfirm){
            if (isConfirm) 
            {
              $.ajaxSetup({
                  headers: {
                      'X-CSRF-TOKEN': '{{csrf_token()}}'
                  }
              });
              $.ajax({
                type: "POST",
                url: url,
                dataType: "JSON",
                data: {"id":id},
                success: function (response) {
                  swal({
                      title: "Deleted", 
                      text: response.message, 
                      type: response.status
                  },function() {
                      location.reload();
                  });
                },
                error: function(xhr) {
                  console.log(xhr.responseText);
                }   
              })
            } else {
               swal.close();
            }
          });
        }
      });
    </script>
    <script>
        $(function() {
          Metis.formValidation();
        });

        $(document).ready(function() {
            var max_fields = 20; //maximum input boxes allowed
            var wrapper = $("#items"); //Fields wrapper
            var add_button = $("#addmore"); //Add button ID

            var x = 1; //initlal text box count
            $(add_button).click(function(e)
            { //on add input button click
                e.preventDefault();
                if(x < max_fields){ //max input box allowed
                x++; //text box increment
                $(wrapper).append('<div class="input-group"><input class="form-control" name="question[new'+x+']" type="text" value=""><div class="input-group-addon"><button type="button" style="padding: 0px 4px;" class="btn btn-danger btn-sm remove_field"><i class="fa fa-close" aria-hidden="true"></i></button></div></div><br>');
            }
            });
             
            $(wrapper).on("click",".remove_field", function(e){ //user click on remove field
              e.preventDefault(); 
              $(this).parent().closest('.input-group').next('br').remove(); 
              $(this).parent().closest('.input-group').remove();
              x--;
            })
        });
    </script>
@endsection

resources/views/admin/trail_session/index.blade.php
@extends('layouts.admin.admin')
@section('uniquecss')

  <link rel="stylesheet" href="{{ url('/') }}/assets/lib/sweetalert/sweetalert.css">
 
@endsection
@section('content')
  <div class="row">
  <div class="col-lg-12">
        <div class="box">
            <header>
                <div class="icons"><i class="fa fa-table"></i></div>
                <h5>{{ __('messages.Trail Sessions') }}</h5>
                <a class="btn btn-primary pull-right" href="{{route('trail-session.create')}}" style="margin-top:4px;">{{ __('messages.Create Session') }}</a>
            </header>
            <div id="collapse4" class="body">
              @include('message')
              
               <table id="user_datatable" class="table table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Session Name</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
                  
            </div>
        </div>
    </div>
</div>
@endsection

@section('uniquescript')
<script src="{{asset('assets/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('assets/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{asset('assets/lib/sweetalert/sweetalert.js')}}"></script>

<script type="text/javascript">

  function deleteRow(obj,asso)
  {

    event.preventDefault(); // prevent form submit
    var msg = "Are you sure?";
    if(asso > 0){
        var msg = "You cannot delete this session because this is associated with question.";
    }
    if(asso > 0){ 
      swal({
          title: msg,
          type: "warning",
          showCancelButton: true,
          showConfirmButton: false,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "Yes",
          cancelButtonText: "Ok",
          closeOnConfirm: false,
          closeOnCancel: false,

        },
        function(isConfirm){
          if (isConfirm) {        
           obj.submit();

          } else {
             swal.close();
          }
        });
    }
    else{
      swal({
          title: msg,
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "Yes",
          cancelButtonText: "No",
          closeOnConfirm: false,
          closeOnCancel: false,

        },
        function(isConfirm){
          if (isConfirm) {        
           obj.submit();

          } else {
             swal.close();
          }
        });
      }
    }
 
    $(function() {
        var table = $('#user_datatable').DataTable({
          stateSave: true,
        processing: true,
        serverSide: true,
        order: [[0, "desc" ]],
        "ajax":{
        "url": '{!! route('trail-session.getdata') !!}',
                "dataType": "json",
                "type": "POST",
                "data":{ _token: "{{csrf_token()}}"}
        },
        columns: [
        { data: 'id', name: 'id', orderable:true },
        { data: 'name', name: 'name', orderable:true },
        { data: 'action', name: 'action', orderable:true  },
        ],
        "columnDefs": [
        { "searchable": false, "targets": 0 }
        ]
        , language: {
        searchPlaceholder: "Search by name"
        },
});
});  


</script>
@endsection