routes/web.php
    $this->post('/service-provider/approve', 'ServiceProviderController@approveUser')->name('sp.user.approve');

    $this->post('/service-provider/decline', 'ServiceProviderController@declineUser')->name('sp.user.decline');
    $this->post('/service-provider/delete-banner-image', 'ServiceProviderController@deleteBannerImage')->name('sp.banner-image-delete');

    $this->post('/service-provider/approval-filter', 'ServiceProviderController@userApprovalFilter')->name('sp.users.filter');
    $this->get('lifetime/{sp_id}', 'ServiceProviderController@showLifeTime')->name('sp.lifetime');
    $this->post('/delete-banner-image', 'ServiceProviderController@deleteBannerImage')->name('admin.banner-image-delete');
    $this->post('/update-banner-image', 'ServiceProviderController@updateGallery')->name('admin.update-gallery');

    $this->post('/service-provider/get-state-list', 'ServiceProviderController@getStateList')->name('sp.get-state-list');
    $this->post('/service-provider/get-city-list', 'ServiceProviderController@getCityList')->name('sp.get-city-list');
    //==================================================================New Category

    $this->get('new-category', 'NewCategoryController@index')->name('new-category.index');
    $this->post('new-category/getdata', 'NewCategoryController@getData')->name('new-category.getdata');

    $this->resource('new-subcategory', 'NewSubCategoryController');
    $this->post('new-subcategory/getdata', 'NewSubCategoryController@getData')->name('new-subcategory.getdata');
    $this->post('new-subcategory/ajax-subcategory', 'NewServiceController@ajaxSubcategory')->name('new-subcategory.ajax');

    $this->resource('new-service', 'NewServiceController');
    $this->post('new-service/getdata', 'NewServiceController@getData')->name('new-service.getdata');

    $this->resource('subservice', 'SubServiceController');
    $this->post('subservice/getdata', 'SubServiceController@getData')->name('subservice.getdata');

    $this->post('subservice/ajax-services', 'SubServiceController@ajaxSubcategoryservice')->name('subservices.ajax');

    $this->resource('service-attribute', 'ServiceAttributeController');
    $this->post('service-attribute/getdata', 'ServiceAttributeController@getData')->name('service-attribute.getdata');

    $this->resource('fitness-type', 'FitnessTypeController');
    $this->post('fitness-type/getdata', 'FitnessTypeController@getData')->name('fitness-type.getdata');
    
    //------------------------------------------------------------
    $this->resource('amenity', 'AmenityController');
    $this->post('amenity/getdata', 'AmenityController@getData')->name('amenity.getdata');

    $this->resource('tier', 'TierController');
    $this->post('tier/getdata', 'TierController@getData')->name('tier.getdata');

    $this->get('category', 'CategoryController@index')->name('category.index');
    $this->post('category/getdata', 'CategoryController@getData')->name('category.getdata');

    $this->resource('subcategory', 'SubCategoryController');
    $this->post('subcategory/getdata', 'SubCategoryController@getData')->name('subcategory.getdata');

    $this->post('subcategory/ajax-subcategory', 'ServiceController@ajaxSubcategory')->name('subcategory.ajax');

    $this->resource('service', 'ServiceController');
    $this->post('service/getdata', 'ServiceController@getData')->name('service.getdata');

    $this->resource('staff', 'StaffController');
    $this->post('staff/getdata', 'StaffController@getData')->name('staff.getdata');
    $this->post('staff/banner-delete', 'StaffController@deleteImageVideos')->name('staff.destroy-file');

    $this->resource('gallery', 'GalleryController');
    $this->post('gallery/getdata', 'GalleryController@getData')->name('gallery.getdata');

    $this->resource('banners', 'BannersController');
    $this->post('banners/getdata', 'BannersController@getData')->name('banners.getdata');
    $this->post('/banners/changeStatus', 'BannersController@StatusUpdate')->name('banners.status.update');

    $this->resource('product', 'ProductController');
    $this->post('product/getdata', 'ProductController@getData')->name('product.getdata');

    $this->resource('tag', 'TagController');
    $this->post('tag/getdata', 'TagController@getData')->name('tag.getdata');

    $this->resource('testimonial', 'TestimonialController');
    $this->post('testimonial/getdata', 'TestimonialController@getData')->name('testimonial.getdata');

    $this->resource('page-section', 'PageSectionController');
    $this->post('page-section/getdata', 'PageSectionController@getData')->name('page-section.getdata');
    $this->post('/page-section/changeStatus', 'PageSectionController@StatusUpdate')->name('page-section.status.update');

    $this->resource('occasion', 'OccasionController');
    $this->post('occasion/getdata', 'OccasionController@getData')->name('occasion.getdata');

    $this->resource('gift-theme', 'GiftThemeController');
    $this->post('gift-theme/getdata', 'GiftThemeController@getData')->name('gifttheme.getdata');
    $this->post('/gift-theme/makePublish', 'GiftThemeController@PublishUpdate')->name('gifttheme.publish.update');

    $this->resource('faq-category', 'FaqCategoryController');
    $this->post('faq-category/getdata', 'FaqCategoryController@getData')->name('faq-category.getdata');

    $this->resource('faq', 'FaqController');
    $this->post('faq/getdata', 'FaqController@getData')->name('faq.getdata');

    $this->resource('contact', 'ContactController');
    $this->post('contact/getdata', 'ContactController@getData')->name('contact.getdata');

    $this->resource('e-card', 'ECardController');
    $this->post('e-card/getdata', 'ECardController@getData')->name('e-card.getdata');
    $this->any('e-card/cancel', 'ECardController@cancel')->name('e-card.cancel');
    $this->get('cancelled-card-view/{id}', 'ECardController@cancelled_card_view')->name('e-card.cancelled_card_view');
    //------------------------offer routes--------------------
    $this->resource('offer', 'OfferController');
    $this->post('offer/getdata', 'OfferController@getData')->name('offer.getdata');

    $this->get('service-provider/pending/offer', 'SpOffersController@pendingOffers')->name('sp.pending.offer');

    $this->get('service-provider/approved/offer', 'SpOffersController@approvedOffers')->name('sp.approved.offer');

    $this->get('service-provider/expired/offer', 'SpOffersController@expiredOffers')->name('sp.expired.offer');

    $this->get('service-provider/spectacular/offer', 'SpOffersController@spectacularOffers')->name('sp.spectacular.offer');


    $this->post('sp/offer/getdata', 'SpOffersController@getData')->name('sp.offer.getdata');
    $this->get('sp/offer/edit/{id}/{name}', 'SpOffersController@edit')->name('sp.offer.edit');
    $this->get('sp/offer/nominate/{id}/{offer_status}', 'SpOffersController@nominateOffer')->name('sp.offer.nominate');
     $this->PATCH('sp/offer/update/{id}', 'SpOffersController@updateOffer')->name('sp.offer.update');

    $this->get('sp/offer/decline/{id}', 'SpOffersController@declineOffer')->name('sp.offer.decline');
    $this->get('sp/offer/view/{id}/{name}', 'SpOffersController@viewOffer')->name('sp.offer.view');
    $this->post('sp/offer/update/nominate/{id}', 'SpOffersController@updateNominateOffer')->name('sp.offer.update.nominate');
     $this->any('sp/offer/destroy/{id}', 'SpOffersController@destroy')->name('sp.offer.destroy');
     $this->post('sp/offer/changeStatus', 'SpOffersController@StatusUpdate')->name('sp.offer.status.update');
     $this->post('sp/offer/changeFeaturedStatus', 'SpOffersController@FeaturedStatusUpdate')->name('sp.offer.featuredstatus.update');

    $this->get('service-provider/services/{id}', 'SpServicesController@index')->name('sp.service.index');
    $this->get('service-provider/services/banner/{id}', 'ServiceProviderController@banner')->name('sp.service.banner');
    $this->post('sp/services/getdata', 'SpServicesController@getData')->name('sp.services.getdata');
    $this->get('sp/services/view/{id}', 'SpServicesController@view')->name('sp.services.view');

    //------------------------offer routes--------------------

   $this->resource('quickFact', 'QuickFactController');
   $this->post('quickFact/getdata', 'QuickFactController@getData')->name('quickFact.getdata');
   $this->post('get-quickFact-subcategory', 'QuickFactController@ajaxSubcategory')->name('get-quickFact-subcategory');
   $this->post('get-quickFact-services', 'QuickFactController@ajaxGetSubcatServices')->name('get-quickFact-services');
   $this->post('get-quickFact-sub-services', 'QuickFactController@ajaxGetSubcatSubServices')->name('get-quickFact-sub-services');

   $this->post('quickfact/banner-delete', 'QuickFactController@deleteBannerImage')->name('quickfact.banner-image-delete');

   $this->resource('reviews', 'ReviewsController');
   $this->post('reviews/getdata', 'ReviewsController@getData')->name('reviews.getdata');
   $this->post('reviews/get-sp-staff-service', 'ReviewsController@getSpStaffServices')->name('get-sp-staff-service');
   $this->post('reviews/ajax-get-sp-searched-staff-service', 'ReviewsController@ajaxGetSpSearchedStaffServices')->name('ajax-get-sp-searched-staff-service');
   $this->post('reviews/filter', 'ReviewsController@getCustomerReviewsFilter')->name('ajax.review.filter');

    $this->post('reviews/status', 'ReviewsController@StatusUpdate')->name('review.status.update');

    $this->get('reviews/show/overall/{sp_id}', 'ReviewsController@showOverallSpReviews')->name('sp.overall.reviews');
    
    $this->get('customer/forum', 'ForumController@index')->name('forum.index');
    $this->post('/forum/get-queries', 'ForumController@getData')->name('forum.queries');
    $this->any('/forum/delete-queries/{slug}', 'ForumController@deleteForumQueries')->name('forum.queries.delete');
    $this->any('/forum/show/{slug}', 'ForumController@viewQuery')->name('forum.queries.view');

resources/views/admin/staff/index.blade.php
@extends('layouts.admin.admin')
@section('uniquecss')

  <link rel="stylesheet" href="{{ url('/') }}/assets/lib/sweetalert/sweetalert.css">
 
@endsection
@section('content')
  <div class="row">
  <div class="col-lg-12">
        <div class="box">
            <header>
                <div class="icons"><i class="fa fa-table"></i></div>
                <h5>Staff</h5>
                <a class="btn btn-primary pull-right" href="{{route('staff.create')}}" style="margin-top:4px;">Create Staff</a>
            </header>
            <div id="collapse4" class="body">
              @include('message')
              
               <table id="user_datatable" class="table table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>Store Name</th>
                        <th>Staff Name</th>
                        <th>Nationality</th>
                        <th>Experience</th>
                        <th>Speciality</th>
                        <th>Provide Home Service</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
                  
            </div>
        </div>
    </div>
</div>
@endsection

@section('uniquescript')
<script src="{{asset('assets/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('assets/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{asset('assets/lib/sweetalert/sweetalert.js')}}"></script>
<script type="text/javascript">

  function deleteRow(obj,asso)
  {
    event.preventDefault(); // prevent form submit
   
    var msg = "Are you sure?";
    if(asso!=''){
        var str = asso;
        var res = str.split("__");
        var msg = "You cannot delete this Staff because "+res+" tables are associated with it.";
                           
   
    }
    if(asso!=''){ 
      swal({
          title: msg,
          type: "warning",
          showCancelButton: true,
          showConfirmButton: false,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "Yes",
          cancelButtonText: "Ok",
          closeOnConfirm: false,
          closeOnCancel: false,

        },
        function(isConfirm){
          if (isConfirm) {        
           obj.submit();

          } else {
             swal.close();
          }
        });
    }
    else{
      swal({
          title: msg,
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "Yes",
          cancelButtonText: "No",
          closeOnConfirm: false,
          closeOnCancel: false,

        },
        function(isConfirm){
          if (isConfirm) {        
           obj.submit();

          } else {
             swal.close();
          }
        });
      }
  }
 
    $(function() {
        var table = $('#user_datatable').DataTable({
          stateSave: true,
        processing: true,
        serverSide: true,
        order: [[0, "desc" ]],
        "ajax":{
        "url": '{!! route('staff.getdata') !!}',
                "dataType": "json",
                "type": "POST",
                "data":{ _token: "{{csrf_token()}}", spid: "{{$spid}}"}
        },
        columns: [
        { data: 'sp_id', name: 'sp_id', orderable:true },
        { data: 'staff_name', name: 'name', orderable:true },
        { data: 'nationality', name: 'nationality', orderable:true  },
        { data: 'experience', name: 'experience', orderable:true  },
        { data: 'speciality', name: 'speciality', orderable:true  },
        { data: 'is_provide_home_service', name: 'is_provide_home_service', orderable:true  },
        { data: 'action', name: 'action', orderable:true  },
        ],
        "columnDefs": [
        { "searchable": false, "targets": 0 }
        ]
        , language: {
        searchPlaceholder: "Search by name and store name"
        },
});
});  


</script>
@endsection