routes/web.php
    //------------------service provider --------------------
    $this->get('/service-provider', 'ServiceProviderController@index')->name('sp.index');
    $this->any('/service-provider/chat-history/{id}', 'ServiceProviderController@spuserChatHistory')->name('sp.spuserChatHistory');
    $this->post('/service-provider/getdata', 'ServiceProviderController@getData')->name('sp.getdata');

    $this->get('/service-provider/changePassword/{slug}', 'ServiceProviderController@changePassword')->name('sp.change-password');
    $this->post('/service-provider/updatePassword', 'ServiceProviderController@doUpdatePassword')->name('sp.update-password');

    $this->post('/service-provider/changeStatus', 'ServiceProviderController@StatusUpdate')->name('sp.users.status.update');
    $this->post('/service-provider/update-tax-status', 'ServiceProviderController@updateTaxVisibility')->name('sp.users.tax.visibility.update');
    
    $this->post('/service-provider/changeFeaturedStatus', 'ServiceProviderController@FeaturedStatusUpdate')->name('sp.users.featuredstatus.update');

    $this->post('/service-provider/changeApproval', 'ServiceProviderController@changeApproval')->name('sp.users.approval.update');

    $this->get('/service-provider/view/{slug}', 'ServiceProviderController@view')->name('sp.view');
    $this->get('/service-provider/edit/{slug}', 'ServiceProviderController@edit')->name('sp.edit');
    $this->post('/service-provider/update', 'ServiceProviderController@update')->name('sp.update');

    $this->post('/service-provider/approve', 'ServiceProviderController@approveUser')->name('sp.user.approve');

    $this->post('/service-provider/decline', 'ServiceProviderController@declineUser')->name('sp.user.decline');
    $this->post('/service-provider/delete-banner-image', 'ServiceProviderController@deleteBannerImage')->name('sp.banner-image-delete');

    $this->post('/service-provider/approval-filter', 'ServiceProviderController@userApprovalFilter')->name('sp.users.filter');
    $this->get('lifetime/{sp_id}', 'ServiceProviderController@showLifeTime')->name('sp.lifetime');
    $this->post('/delete-banner-image', 'ServiceProviderController@deleteBannerImage')->name('admin.banner-image-delete');
    $this->post('/update-banner-image', 'ServiceProviderController@updateGallery')->name('admin.update-gallery');

    $this->post('/service-provider/get-state-list', 'ServiceProviderController@getStateList')->name('sp.get-state-list');
    $this->post('/service-provider/get-city-list', 'ServiceProviderController@getCityList')->name('sp.get-city-list');
    //==================================================================New Category

    $this->get('new-category', 'NewCategoryController@index')->name('new-category.index');
    $this->post('new-category/getdata', 'NewCategoryController@getData')->name('new-category.getdata');

    $this->resource('new-subcategory', 'NewSubCategoryController');
    $this->post('new-subcategory/getdata', 'NewSubCategoryController@getData')->name('new-subcategory.getdata');
    $this->post('new-subcategory/ajax-subcategory', 'NewServiceController@ajaxSubcategory')->name('new-subcategory.ajax');

    $this->resource('new-service', 'NewServiceController');
    $this->post('new-service/getdata', 'NewServiceController@getData')->name('new-service.getdata');

    $this->resource('subservice', 'SubServiceController');
    $this->post('subservice/getdata', 'SubServiceController@getData')->name('subservice.getdata');

    $this->post('subservice/ajax-services', 'SubServiceController@ajaxSubcategoryservice')->name('subservices.ajax');

    $this->resource('service-attribute', 'ServiceAttributeController');
    $this->post('service-attribute/getdata', 'ServiceAttributeController@getData')->name('service-attribute.getdata');

    $this->resource('fitness-type', 'FitnessTypeController');
    $this->post('fitness-type/getdata', 'FitnessTypeController@getData')->name('fitness-type.getdata');
    
    //------------------------------------------------------------
    $this->resource('amenity', 'AmenityController');
    $this->post('amenity/getdata', 'AmenityController@getData')->name('amenity.getdata');

    $this->resource('tier', 'TierController');
    $this->post('tier/getdata', 'TierController@getData')->name('tier.getdata');

    $this->get('category', 'CategoryController@index')->name('category.index');
    $this->post('category/getdata', 'CategoryController@getData')->name('category.getdata');

    $this->resource('subcategory', 'SubCategoryController');
    $this->post('subcategory/getdata', 'SubCategoryController@getData')->name('subcategory.getdata');

    $this->post('subcategory/ajax-subcategory', 'ServiceController@ajaxSubcategory')->name('subcategory.ajax');

    $this->resource('service', 'ServiceController');
    $this->post('service/getdata', 'ServiceController@getData')->name('service.getdata');

    $this->resource('staff', 'StaffController');
    $this->post('staff/getdata', 'StaffController@getData')->name('staff.getdata');
    $this->post('staff/banner-delete', 'StaffController@deleteImageVideos')->name('staff.destroy-file');

    $this->resource('gallery', 'GalleryController');
    $this->post('gallery/getdata', 'GalleryController@getData')->name('gallery.getdata');

    $this->resource('banners', 'BannersController');
    $this->post('banners/getdata', 'BannersController@getData')->name('banners.getdata');
    $this->post('/banners/changeStatus', 'BannersController@StatusUpdate')->name('banners.status.update');

    $this->resource('product', 'ProductController');
    $this->post('product/getdata', 'ProductController@getData')->name('product.getdata');

    $this->resource('tag', 'TagController');
    $this->post('tag/getdata', 'TagController@getData')->name('tag.getdata');

    $this->resource('testimonial', 'TestimonialController');
    $this->post('testimonial/getdata', 'TestimonialController@getData')->name('testimonial.getdata');

    $this->resource('page-section', 'PageSectionController');
    $this->post('page-section/getdata', 'PageSectionController@getData')->name('page-section.getdata');
    $this->post('/page-section/changeStatus', 'PageSectionController@StatusUpdate')->name('page-section.status.update');

    $this->resource('occasion', 'OccasionController');
    $this->post('occasion/getdata', 'OccasionController@getData')->name('occasion.getdata');

    $this->resource('gift-theme', 'GiftThemeController');
    $this->post('gift-theme/getdata', 'GiftThemeController@getData')->name('gifttheme.getdata');
    $this->post('/gift-theme/makePublish', 'GiftThemeController@PublishUpdate')->name('gifttheme.publish.update');

    $this->resource('faq-category', 'FaqCategoryController');
    $this->post('faq-category/getdata', 'FaqCategoryController@getData')->name('faq-category.getdata');

    $this->resource('faq', 'FaqController');
    $this->post('faq/getdata', 'FaqController@getData')->name('faq.getdata');

    $this->resource('contact', 'ContactController');
    $this->post('contact/getdata', 'ContactController@getData')->name('contact.getdata');

    $this->resource('e-card', 'ECardController');
    $this->post('e-card/getdata', 'ECardController@getData')->name('e-card.getdata');
    $this->any('e-card/cancel', 'ECardController@cancel')->name('e-card.cancel');
    $this->get('cancelled-card-view/{id}', 'ECardController@cancelled_card_view')->name('e-card.cancelled_card_view');
    //------------------------offer routes--------------------
    $this->resource('offer', 'OfferController');
    $this->post('offer/getdata', 'OfferController@getData')->name('offer.getdata');

    $this->get('service-provider/pending/offer', 'SpOffersController@pendingOffers')->name('sp.pending.offer');

    $this->get('service-provider/approved/offer', 'SpOffersController@approvedOffers')->name('sp.approved.offer');

    $this->get('service-provider/expired/offer', 'SpOffersController@expiredOffers')->name('sp.expired.offer');

    $this->get('service-provider/spectacular/offer', 'SpOffersController@spectacularOffers')->name('sp.spectacular.offer');


    $this->post('sp/offer/getdata', 'SpOffersController@getData')->name('sp.offer.getdata');
    $this->get('sp/offer/edit/{id}/{name}', 'SpOffersController@edit')->name('sp.offer.edit');
    $this->get('sp/offer/nominate/{id}/{offer_status}', 'SpOffersController@nominateOffer')->name('sp.offer.nominate');
     $this->PATCH('sp/offer/update/{id}', 'SpOffersController@updateOffer')->name('sp.offer.update');

    $this->get('sp/offer/decline/{id}', 'SpOffersController@declineOffer')->name('sp.offer.decline');
    $this->get('sp/offer/view/{id}/{name}', 'SpOffersController@viewOffer')->name('sp.offer.view');
    $this->post('sp/offer/update/nominate/{id}', 'SpOffersController@updateNominateOffer')->name('sp.offer.update.nominate');
     $this->any('sp/offer/destroy/{id}', 'SpOffersController@destroy')->name('sp.offer.destroy');
     $this->post('sp/offer/changeStatus', 'SpOffersController@StatusUpdate')->name('sp.offer.status.update');
     $this->post('sp/offer/changeFeaturedStatus', 'SpOffersController@FeaturedStatusUpdate')->name('sp.offer.featuredstatus.update');

    $this->get('service-provider/services/{id}', 'SpServicesController@index')->name('sp.service.index');
    $this->get('service-provider/services/banner/{id}', 'ServiceProviderController@banner')->name('sp.service.banner');
    $this->post('sp/services/getdata', 'SpServicesController@getData')->name('sp.services.getdata');
    $this->get('sp/services/view/{id}', 'SpServicesController@view')->name('sp.services.view');

    //------------------------offer routes--------------------

   $this->resource('quickFact', 'QuickFactController');
   $this->post('quickFact/getdata', 'QuickFactController@getData')->name('quickFact.getdata');
   $this->post('get-quickFact-subcategory', 'QuickFactController@ajaxSubcategory')->name('get-quickFact-subcategory');

resources/views/admin/subservice/ajaxSubcategoryservice.blade.php
@if($service_arr)
{{ Form::select('parent_service_id', $service_arr,null,['class' => 'form-control validate[required]','placeholder'=>'Select Service Name','id'=>'parent_service_id']) }}
@endif

resources/views/admin/subservice/create.blade.php
@extends('layouts.admin.admin')

@section('uniquecss')

  <link rel="stylesheet" href="{{ url('/') }}/assets/lib/plupload/js/jquery.plupload.queue/css/jquery.plupload.queue.css">
  <link rel="stylesheet" href="{{ url('/') }}/assets/lib/jquery.gritter/css/jquery.gritter.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/Uniform.js/2.1.2/themes/default/css/uniform.default.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.theme.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/validationEngine.jquery.min.css">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/clockpicker/0.0.7/bootstrap-clockpicker.min.css">
@endsection

@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <header class="dark">
                <div class="icons"><i class="fa fa-check"></i></div>
                <h5>{{$title}}</h5>
          

            </header>
             @include('message')
            <div id="collapse2" class="body">
                <!-- <form class="form-horizontal" id="popup-validation"> -->
                {!! Form::open(['route' => 'subservice.store', 'method' => 'POST', 'class' => 'form-horizontal','id' => 'popup-validation','enctype' => 'multipart/form-data']) !!}
                {{ csrf_field() }}
 
                    <div class="form-group">
                        {{Form::label('category_name', 'Category Name', ['class' => 'control-label col-lg-4'])}}
                        <div class="col-lg-4">
                            {{ Form::select('cat_id', $categories,null,['class' => 'form-control validate[required]','id'=>'category','placeholder'=>'Select Categories']) }}
                        </div>
                    </div>

                    <div class="form-group">
                        {{Form::label('category_name', 'Sub Category Name', ['class' => 'control-label col-lg-4'])}}
                        <div class="col-lg-4" id="subcat_div">
                            {{ Form::select('subcat_id', [],null,['class' => 'form-control validate[required] sub_category','placeholder'=>'Select Sub Categories']) }}
                        </div>
                    </div>
                    
                    <div class="form-group">
                        {{Form::label('parent_service_id', 'Service Name', ['class' => 'control-label col-lg-4'])}}
                        <div class="col-lg-4" id="subcat_services_div">
                            {{ Form::select('parent_service_id', [],null,['class' => 'form-control validate[required]','placeholder'=>'Select Service Name','id'=>'parent_service_id']) }}
                        </div>
                    </div>
                    <div class="form-group">
                        {{Form::label('name', 'Sub Service Name', ['class' => 'control-label col-lg-4'])}}
                        <div class="col-lg-4">
                            {{ Form::text('name','', ['class' => 'form-control validate[required]', 'maxlength' => '50']) }}
                        </div>
                    </div>

                    <div class="form-group">
                        {{Form::label('name_ar', 'Sub Service Name(Arabic)', ['class' => 'control-label col-lg-4'])}}
                        <div class="col-lg-4">
                            {{ Form::text('name_ar','', ['class' => 'form-control validate[required]', 'maxlength' => '50']) }}
                        </div>
                    </div>

                    <div class="form-group">
                        {{Form::label('price', 'Beutics Price', ['class' => 'control-label col-lg-4'])}}
                        <div class="col-lg-4">
                            {{ Form::text('price','', ['class' => 'form-control']) }}
                        </div>
                    </div>

                    <div class="form-group">
                        {{Form::label('description', 'Description', ['class' => 'control-label col-lg-4'])}}
                        <div class="col-lg-4">
                            {{ Form::textarea('description','', ['class' => 'form-control validate[required]','rows'=>'2', 'maxlength' => '1000']) }}
                        </div>
                    </div>

                     <div class="form-group">
                        {{Form::label('description_ar', 'Description(Arabic)', ['class' => 'control-label col-lg-4'])}}
                        <div class="col-lg-4">
                            {{ Form::textarea('description_ar','', ['class' => 'form-control validate[required]','rows'=>'2', 'maxlength' => '1000']) }}
                        </div>
                    </div>

                    <div class="form-group">
                        {{Form::label('time', 'Service Time', ['class' => 'control-label col-lg-4'])}}
                        <div class="input-group  col-lg-4">
                      
                            <!-- {{ Form::text('time',null, ['class' => 'form-control validate[required]','autocomplete'=>'off']) }} -->
                            <div class="hourbox">
                            <div class="hhbox control-label">Hours</div>
                            <div class="hhbox quantity">
                             <input type="number" name="serviceTimeHour" placeholder="Hours" value='0' min="0" max="23" step="1" class="validate[required]">
                             </div>
                           </div>
                           <div class="hourbox">
                            <div class="hhbox control-label">Minutes</div>
                             <div class="hhbox quantity">
                          <input type="number" name="serviceTimeMin" placeholder="Minutes" value='0' min="0" max="59" step="1" class="validate[required]">
                            </div>
                          </div>
                        </div>

                    </div>

                  <!--   <div class="form-group">
                        {{Form::label('time', 'Add On Services', ['class' => 'control-label col-lg-4'])}}
                        <div class="col-lg-4">
                           {{ Form::select('addon[]', $services,null,['class' => 'form-control myselect','data-live-search' => 'true','multiple']) }}
                        </div>
                    </div> -->
                    

                    <div class="form-actions no-margin-bottom">
                        <input type="submit" value="Submit" class="btn btn-primary">
                    </div>
                    <br><br><br><br>
                </form>
            </div>
        </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
@endsection
@section('uniquescript')
    <script src="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/jquery.validationEngine.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/languages/jquery.validationEngine-en.min.js"></script>

     <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/holder/2.4.1/holder.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/Uniform.js/2.1.2/jquery.uniform.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <script>
        $(function() {
          Metis.formValidation();
        });
    </script>
<script type="text/javascript">
    $(document).ready(function(){
            jQuery('<div class="quantity-nav"><div class="quantity-button quantity-up">+</div><div class="quantity-button quantity-down">-</div></div>').insertAfter('.quantity input');
    jQuery('.quantity').each(function() {
      var spinner = jQuery(this),
        input = spinner.find('input[type="number"]'),
        btnUp = spinner.find('.quantity-up'),
        btnDown = spinner.find('.quantity-down'),
        min = input.attr('min'),
        max = input.attr('max');

      btnUp.click(function() {
        var oldValue = parseFloat(input.val());
        if (oldValue >= max) {
          var newVal = oldValue;
        } else {
          var newVal = oldValue + 1;
        }
        spinner.find("input").val(newVal);
        spinner.find("input").trigger("change");
      });

      btnDown.click(function() {
        var oldValue = parseFloat(input.val());
        if (oldValue <= min) {
          var newVal = oldValue;
        } else {
          var newVal = oldValue - 1;
        }
        spinner.find("input").val(newVal);
        spinner.find("input").trigger("change");
      });

    });
}); 
    </script>
    <script type="text/javascript">
        $("#category").change(function()
        {
            var id = $(this).val();
            
            jQuery.ajax({
            url: '{{route('new-subcategory.ajax')}}',
            type: 'POST',
            data:{cat_id:id},
            headers: {
            'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
            },
            success: function (response) {
              $("#subcat_div").html(response);
            }
            });
              
        });

        $("body").on('change', '.sub_category', function()
        {
            var id = $(this).val();
            var cat_id = $("#category option:selected").val();
            
            jQuery.ajax({
            url: '{{route('subservices.ajax')}}',
            type: 'POST',
            data:{subcat_id:id,cat_id:cat_id},
            headers: {
            'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
            },
            success: function (response) {
              $("#subcat_services_div").html(response);
            }
            });
              
        });
    </script>
    <script type="text/javascript">
      $(".myselect").select2();
    </script>

     <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/clockpicker/0.0.7/bootstrap-clockpicker.min.js"></script>

    <script type="text/javascript">
        $('.clockpicker').clockpicker({'donetext':'Done'});
    </script>


@endsection

resources/views/admin/subservice/index.blade.php
@extends('layouts.admin.admin')
@section('uniquecss')

  <link rel="stylesheet" href="{{ url('/') }}/assets/lib/sweetalert/sweetalert.css">
 
@endsection
@section('content')
  <div class="row">
  <div class="col-lg-12">
        <div class="box">
            <header>
                <div class="icons"><i class="fa fa-table"></i></div>
                <h5>Sub Services</h5>
                <a class="btn btn-primary pull-right" href="{{route('subservice.create')}}" style="margin-top:4px;">Create Sub Service</a>
            </header>
            <div id="collapse4" class="body">
              @include('message')
              
               <table id="user_datatable" class="table table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Name(Arabic)</th>
                        <th>Parent Service</th>
                        <th>Created At</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
                  
            </div>
        </div>
    </div>
</div>
@endsection

@section('uniquescript')
<script src="{{asset('assets/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('assets/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{asset('assets/lib/sweetalert/sweetalert.js')}}"></script>
<script type="text/javascript">

  function deleteRow(obj,asso)
  {
    event.preventDefault(); // prevent form submit

    var msg = "Are you sure?";
    if(asso!=''){
        var str = asso;
        var res = str.replace("__", ", ");
        var msg = "You cannot delete this Service because "+res+" tables are associated with it.";
                           
   
    }
    if(asso!=''){ 
      swal({
          title: msg,
          type: "warning",
          showCancelButton: true,
          showConfirmButton: false,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "Yes",
          cancelButtonText: "Ok",
          closeOnConfirm: false,
          closeOnCancel: false,

        },
        function(isConfirm){
          if (isConfirm) {        
           obj.submit();

          } else {
             swal.close();
          }
        });
    }
    else{
      swal({
          title: msg,
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "Yes",
          cancelButtonText: "No",
          closeOnConfirm: false,
          closeOnCancel: false,

        },
        function(isConfirm){
          if (isConfirm) {        
           obj.submit();

          } else {
             swal.close();
          }
        });
      }
  }
 
    $(function() {
        var table = $('#user_datatable').DataTable({
          stateSave: true,
        processing: true,
        serverSide: true,
        order: [[0, "desc" ]],
        "ajax":{
        "url": '{!! route('subservice.getdata') !!}',
                "dataType": "json",
                "type": "POST",
                "data":{ _token: "{{csrf_token()}}"}
        },
        columns: [
        { data: 'name', name: 'name', orderable:true },
        { data: 'name_ar', name: 'name_ar', orderable:true },
        { data: 'parent_service_id', name: 'parent_service_id', orderable:true },
        { data: 'created_at', name: 'created_at', orderable:true  },
        { data: 'action', name: 'action', orderable:true  },
        ],
        "columnDefs": [
        { "searchable": false, "targets": 0 }
        ]
        , language: {
        searchPlaceholder: "Search by name"
        },
});
});  


</script>
@endsection